name: CI Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: pip install -r requirements.txt

      - name: Lint
        run: flake8 .

      - name: Tests
        run: nosetests
